name: tknp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  animated_theme_switcher: 
  cached_network_image:
  carousel_pro: ^1.0.0
  cupertino_stackview: 
  data_connection_checker: 
  # flutter_plugin_pdf_viewer: any
  font_awesome_flutter: ^9.0.0-nullsafety
  # get_it:
  google_sign_in: 
  http: any
  intro_views_flutter: 
  modal_progress_hud: 
  palette_generator: 
  provider: ^5.0.0-nullsafety.5
  share: ^2.0.0-nullsafety.2
  # transformer_page_view: ^0.1.6
  url_launcher: 
  webview_flutter: 
  animations: ^2.0.0-nullsafety.0
  wiredash: 
  path_provider: null
  shared_preferences: 
  # flutter_pdfview: ^1.0.0+6
  image_picker: any
  dio: any
  # package_info: ^0.4.0+13
  auto_size_text:
  device_preview: 
  cuid: 
  permission_handler: 
  # flutter_typeahead: ^1.8.1
  # flutter_full_pdf_viewer: ^1.0.6
  stacked: 
  injectable: null
  logger: 
  flutter_mailer: 
  expansion_tile_card:
  mime: null
  json_annotation: 
  percent_indicator: 
  auto_route: 
  rxdart: null
  stacked_services: null
  get: 
  # avatar_glow: ^1.1.0
  simple_url_preview: null
  lottie: 
  file_picker: 
  connectivity: 

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 400
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
